Copy-Item .\Release\CCDPlugStarshootG.dll .\Installer
Copy-Item .\starshootgsdk\win\starshootg.dll .\Installer
Copy-Item .\GainControlSSG\bin\Release\net6.0-windows\GainControlSSG.dll .\Installer
Copy-Item .\GainControlSSG\bin\Release\net6.0-windows\GainControlSSG.exe .\Installer
Copy-Item .\GainControlSSG\bin\Release\net6.0-windows\Newtonsoft.Json.dll .\Installer
Copy-Item .\GainControlSSG\bin\Release\net6.0-windows\Default.json .\Installer
Copy-Item .\GainControlSSG\bin\Release\net6.0-windows\Default.json .\Installer\Gain.json
Copy-Item .\GainControlSSG\bin\Release\net6.0-windows\GainControlSSG.runtimeconfig.json .\Installer\
Copy-Item .\SettingsSSG\bin\Release\net6.0-windows\SettingsSSG.dll .\Installer\
Copy-Item .\SettingsSSG\bin\Release\net6.0-windows\SettingsSSG.exe .\Installer\
Copy-Item .\SettingsSSG\bin\Release\net6.0-windows\SettingsSSG.runtimeconfig.json .\Installer\
